import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import { ReduxProvider } from "@/providers/ReduxProvider";
import "./globals.css";
import HeaderWrapper from "@/components/organisms/header/HeaderWrapper";
import FooterWrapper from "@/components/organisms/footer/FooterWrapper";
import { Toaster } from "react-hot-toast";
import BackToTop from "@/components/molecules/global/BackToTop";
import { getCategories } from "@/actions/getCategory";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Favoor E-commerce website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cate = await getCategories();

  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${montserrat.variable} ${roboto.variable} antialiased bg-light-gray overflow-x-hidden font-montserrat`}
      >
        <ReduxProvider>
          <HeaderWrapper categories={cate} />

          {children}
          <Toaster position="top-center" reverseOrder={false} />
          <FooterWrapper />
          <BackToTop />
        </ReduxProvider>
      </body>
    </html>
  );
}
